// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.4
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MessageTypes
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class LogMessage {
			private string _IPS;
		private string _Message;
		private IDictionary<string,System.String> _Tags;
		private MessageTypes.LogLevel _Severity;
		
		public string IPS
		{
			get
			{
				return this._IPS;
			}
			set
			{
				this._IPS = value;
			}
		}
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				this._Message = value;
			}
		}
		public IDictionary<string,System.String> Tags
		{
			get
			{
				return this._Tags;
			}
			set
			{
				this._Tags = value;
			}
		}
		public MessageTypes.LogLevel Severity
		{
			get
			{
				return this._Severity;
			}
			set
			{
				this._Severity = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.IPS;
			case 1: return this.Message;
			case 2: return this.Tags;
			case 3: return this.Severity;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.IPS = (System.String)fieldValue; break;
			case 1: this.Message = (System.String)fieldValue; break;
			case 2: this.Tags = (IDictionary<string,System.String>)fieldValue; break;
			case 3: this.Severity = (MessageTypes.LogLevel)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}